title: Jeewoong Kim
url: "jeewoongkim.github.io"
baseurl: ""

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no 
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

plugins:
 - jemoji

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
 - name: "Teaching"
   link: "teaching"
 - name: "CV"
   link: "jeewoong-cv.pdf"
